version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URL:latest -t $ECR_REPO_URL:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $ECR_REPO_URL:latest
      - docker push $ECR_REPO_URL:$IMAGE_TAG
      - echo Build completed
